class Travel {
  String name;
  String location;
  String url;
  String description;
  double latitude;
  double longitude;

  Travel(this.name, this.location, this.url, this.description, this.latitude,
      this.longitude);

  static List<Travel> generateTravelBlog() {
    return [
      Travel(
          'Nine Arch',
          'Ella',
          'assets/images/ella.jpg',
          'Built at 3100m above sea level, among the craggy peaks of the Central Highlands; the Nine Arches forms a viaduct between the Demodara and Ella Railway stations. Built entirely out of brick, rock and cement; without a single piece of steel; the bridge has stood solid from 1921, its time of creation.\nAccording to history, the bridge was built by the locals using such materials; when the construction came to a standstill from the lack of steel caused by World War I. But, in addition to this history; lore abounds the creation of the bridge. The most famous story speaks of a man named P. K. Appuhami, who lived in the Kappatipola area in Melimada. Born in 1870, Appuhami was a famed traditional drummer and devil dancer (a ritual dance form). \nOne day, while returning home gloomily as he lost a competition, Appuhami was seen by a British official. The man was extremely frightened by the devilish apparition (Appuhami was still in his dance costume) at the beginning; but soon became quite friendly. Learning that the strange foreigner was in his area to construct a railway; Appuhami assisted by supplying him with labour from the local villages.But things did not go smoothly with the railway construction. They found that they were unable to bridge a large gap between two hills; as there was a quagmire in the valley in between. It was not possible to create firm anchoring, due to the marshy ground. \nOn learning this, Appuhami requested to take over the bridge project. While he was rejected initially, they agreed later; as he had gained their trust with his assistance and friendship. As the story goes, Appuhami started working on the bridge in 1913. He solved the issue of the unstable ground by toppling giant rocks into the space; until a firm bed of rocks was formed. He then created the bridge’s brick columns over this bed and continued with the construction of the bridge. The methods of constructions used by Appuhami proved to be so intuitive and cost effective; that he finished the entire project, which was intended to continue for many years, within a single year at a fraction of the original cost planned. \nThe British officials were so shocked that the ‘savages’ had finished such a huge project so easily; that they refused to believe its structural integrity. At this point Appuhami is said to have sworn to the strength of the structure by saying he would prove it by lying under the bridge; when the railway line was used for the first time.',
          6.876720141030005,
          81.06080875618848),
      Travel(
          'Sigiriya Rock',
          'Sigiriya',
          'assets/images/sigiriya.jpg',
          "Sigiriya is one of Sri Lanka’s most popular tourist attractions and with good reason. This ruined, fifth century city has some extraordinary features, including moat and wall fortifications, elaborately landscaped gardens, and a monastery. But it is the two-hundred metre high granite rock that stands out from these ruins that is undoubtedly the star attraction, with its exquisite frescoes and the remains of a royal palace on the summit. I was looking forward to seeing the frescoes at Sigiriya after seeing images of them. However, I had not seen images of the stairs that tourists must ascend to see the paintings. Unfortunately, I have an unreasonable fear of heights, which isn't always a good thing for an ancient art archaeologist. I should add that because of that concern, I have never skipped a sight or been unable to take or film photographs up close. There have been a couple moments when it came really close! You walk past the ruins of a once-beautiful planted garden – complete with lakes and terraces – on your way to Lion Rock. A two-hundred-meter-high granite monolith looms ahead of the trail. My heart pumped louder and quicker with each stride. The ascent begins with a brick stairway at the bottom of the stairs and then transitions to an iron staircase built into the side of the granite rock face. It didn't help that there were swarms of people mounting the steps ahead of me — acrophobia is, after all, an illogical fear. In retrospect, the climb did not appear to be particularly difficult, but I recall being relieved when it was over. Climbing Sigiriya Rock was one of my most memorable archaeological visits because of the delicately painted frescoes and the amazing wall of graffiti, some of which had been left by Buddhist monks in the seventh and eighth centuries, and then walking among the amazing ruins of the royal palace on the flat topped outcrop.",
          7.957286046571522,
          80.76005346885206),
      Travel(
          'Dansinane',
          'Nuwara Eliya',
          'assets/images/Waterfalls-Srilanka.jpg',
          "This stunning 100-meter-high Dunsinane waterfall (Pundalu Oya Ella) cascades in a spectacular series of steps before pouring into the Pundalu Oya (river), the Kotmale River, and eventually the Kotmale Reservoir. Pundalu Oya is the closest town. Dunsinane Falls, Dunsinan-Sheen Falls, Dansinanshin Falls, and Pundalu Oya Ella are all names for the same waterfall. Between two tea plantations, Dunsinan on one side and Sheen Estate on the other, this waterfall may be found. As a result, this water fall is known as Dunsinane Falls, which combines both names. The road bridge divides the waterfall into two halves. The top part drops 30 meters over a huge rocky ledge, creating a sheet of water. From the bridge, this is the only section of the waterfall that can be seen clearly. The second section, which is around 70 meters high, is concealed beneath the bridge. Due to the steepness of the location, getting to the bottom of the fall is difficult, and the Upper Kotmale Project has classified the region spanning the river below as a high security zone.",
          7.006260828318145,
          80.68816755496442),
      Travel(
          "Adam's Peak",
          "Adam's Peak",
          'assets/images/adams_peak.jpg',
          "Between two tea plantations, Dunsinan on one side and Sheen Estate on the other, this waterfall may be found. As a result, this water fall is known as Dunsinane Falls, which combines both names. The road bridge divides the waterfall into two halves. The top part drops 30 meters over a huge rocky ledge, creating a sheet of water. From the bridge, this is the only section of the waterfall that can be seen clearly. The second section, which is around 70 meters high, is concealed beneath the bridge. Due to the steepness of the location, getting to the bottom of the fall is difficult, and the Upper Kotmale Project has classified the region spanning the river below as a high security zone. According to Siam's tradition, the Buddha left the print of his left foot on Adam's Peak and then walked over to Siam (now Thailand) in one stride, leaving the impression of his right foot. It's called Phra Sat, and it's intended to look like the footprint on Adam's Peak and be around the same size. Broad stairs go up to this walled enclosure with a tower-like structure atop the rock. The area marked off as containing the Buddha's foot impression is approximately five feet seven inches long and two feet seven inches wide. The Buddha's right foot is claimed to be imprinted in a hole in the rock in Thailand, which is roughly five feet long and two feet wide. Buddhists credit the Buddha's global size to the fact that he was roughly 35 feet tall, according to popular belief. The true footprint on Adam's Peak is said to be hidden beneath the visible granite in jewels, and Hindus believe it is that of the deity Siva. The rock's Tamil name (Civan-oli-pata) translates to 'the mountain road of Siva's light.' Muslims think the imprint belongs to Adam (hence the name Adam's Peak), whereas Christians believe it belongs to St. Thomas, Jesus' disciple. A shrine beside the rock has images of the God Saman, one of which is made of silver, and a Brahmin priest officiates at the shrine. A little table stands in front of the shrine, where pilgrims deposit camphor and lit candles.",
          6.8103245719805265,
          80.49934524294923),
      Travel(
          'Jaffna Port',
          'Jaffna',
          'assets/images/jaffa_port.jpg',
          "Next to Tel Aviv, Jaffa, the world's oldest seaport, is home to a dynamic multiethnic population of Muslims, Christians, and Jews. Jaffa has been a port city for more than 4,000 years, according to archaeology and historical archives, and it is from here that Jonah (of Jonah and the Whale) sailed sail. The harbor had grown abandoned until recently, but it now teems with life and culture, from seafood restaurants and organic-coffee cafés to bookstores and theaters, thanks to substantial improvements. With various art galleries and studios, the Old Port (also known as Namal Yafo) serves as a type of artist colony. The vistas, especially around sunset, are spectacular.",
          9.66234843630827,
          80.00848365373716),
      Travel(
          'Boburu Ella',
          'Nuwara eliya',
          'assets/images/boduru_ella.webp',
          "A gorgeous, magnificent waterfall Boburu Ella (also known as Perawella fall) is a waterfall located in the Sita Eliya Kandepola forest reserve, which is part of the Uva Paranagama divisional administrative boundary between Nuwara Eliya and Badulla. It's one of the most well-known tourist destinations on the island's hill country. It is Sri Lanka's largest and most impressive waterfall. The Boburu Ella is a single waterfall as well as a cluster of ten smaller forest waterfalls that have developed next to each other. Together, they form an astounding scene that will live on in your memory forever. The waterfall reaches a height of 50 meters. Between 1,500 and 2,000 meters above sea level, the waterfall may be found. A stroll through the Sita Eliya Kandapola Forest Reserve's wildness, up the trail to the top of Bomburu Ella Falls, provides fantastic views of nearby waterfalls of varied heights and forms. The Pedro Scout Camp, which focuses on scout leader training, as well as Nuwara Eliya's sports shooting range, will be nearby. The waters of the Bomburu Ella Fall have been channeled to a nearby powerhouse, where they are used for agriculture. The Bomburu reservoir, which is named for the nearby waterfall, is fed by several of the lesser-known waterfalls that make up Bomburu Ella.",
          6.947502995672652,
          80.83074568195178),
      Travel(
          'Hortain Plains',
          'Nuwara eliya',
          'assets/images/Horton_Plains.jpg',
          "Horton Plains in Sri Lanka is the country's coldest and windiest area. Montane evergreen forests, grasslands, marshy regions, and aquatic habitats are among the ecosystems found there. Horton Plains, at an elevation of 2,100 meters above sea level, covers 3,169 hectares of the island's highest tableland. Horton Plains was designated as a UNESCO World Heritage Site on July 30, 2010, due to its huge number of indigenous plant and animal species. The Horton Plains, its environs, forests, and the adjacent Peak Wilderness make up Sri Lanka's most significant catchment basin for nearly all major rivers. The plains are particularly notable for their visual beauty and conservation value, since they hold the majority of the country's wet and montane zones' ecosystems and rare flora and animals. The most widespread region of Montane cloud forest on the island may be found on the western slopes. Horton Plains is more than just a naturalist's paradise. Because the vast biodiversity of Horton Plains is still largely untapped, it provides tremendous opportunity for educational and scientific purposes. All Sri Lankans have a responsibility to protect Horton Plains.",
          6.803058620932046,
          80.80910712612786),
      Travel(
          'Jungle Beach',
          'Galle',
          'assets/images/jungle_beach.jpg',
          "Jungle Beach is a beautiful beach tucked in a wooded environment located west of Unawatuna. It is one of Sri Lanka's hidden jewels, with everything you need to make your vacation one to remember. Due to its quiet position, the site preserves its pure natural appeal all year. Water sports such as snorkeling, scuba diving, swimming, boat rides, and more are available at Jungle Beach. The reefs that stick out of the water a few meters offshore are an excellent spot for snorkeling, since they present you to the region's unusual marine life. You'll see moray eels, crabs, barracudas, trigger fish, and a variety of other reef-dwelling critters in addition to schools of colorful fish. Whale watching, exploring ancient sites, jungle trekking, and many more things are available in Jungle Beach. At Forest Beach, you'll find top-notch resorts and cabins with luxurious facilities and a calm hideaway in the heart of the jungle. Private paths connect the resorts and cottages to the peaceful shoreline soothed by the lapping waves of the Indian Ocean. Traditional Sri Lankan cuisine may be enjoyed at a community restaurant or in a coastal restaurant with private dining. In a nutshell, Jungle Beach is a hidden gem that invites you to discover it and enjoy your holiday in elegance and luxury.",
          6.018723972370636,
          80.2394131645077),
      Travel(
          'Mirissa Beach',
          'Matara',
          'assets/images/mirissa.jpg',
          "Mirissa is a tiny town on Sri Lanka's south coast, located in the Southern Province's Matara District. It's about 150 kilometers (93 miles) south of Colombo, and it's at a height of 4 meters (13 feet) above sea level. Mirissa is a renowned tourist destination due to its beach and nightlife. It's also a fishing port and one of the best places on the island to see whales and dolphins. Mirissa is one of southern Sri Lanka's most popular beach getaways, and with good reason! Beautiful Sri Lankan beaches, amazing surfing waves, and waterways abounding with marine life, from turtles to enormous blue whales, abound in this area. Spend your days lounging in your hammock with fresh coconuts, eating amazing meals from coastal eateries, and zipping around on your motorcycle. Four days is the ideal length of time to soak in the laid-back lifestyle of this sunny beach town while enjoying all of Mirissa's major attractions.",
          5.944827904779861,
          80.45918933721013),
      Travel(
          'Pinnawala Elephant Phase',
          'Pinnawala',
          'assets/images/pinnawala_elephant.jpg',
          "The Pinnawala Elephant Orphanage (PEO) has a unique approach to ex-situ animal care, as the name indicates. Its renown and success have spread not just inside the country, but also across the world, making Pinnawala synonymous with the Sri Lankan Elephant. On the 16th of February 1975, the late Hon. Minister Kalugalle realized the project, which is now home to 93 elephants. Pinnawala was a fairly distant location with rich coconut plantations at the time, and most importantly, a place where mahouts were plentiful. The elephants' enormous water requirements are further augmented by the existence of 'Ma oya' flowing nearby. Each animal is also given 76 kg of green matter each day, as well as 2 kg of rice bran and maize from a feeding bag. The orphanage, which claims to house the world's biggest herd of captive elephants, is immensely popular, and many Sri Lankan and foreign visitors visit it on a regular basis. The elephants bathing, which is quite a show, is undoubtedly the primary attraction.",
          7.301283511752076,
          80.38714388840943),
      Travel(
          'Watadage',
          'Polonnaruwa',
          'assets/images/polonnaruwa.jpg',
          "After the collapse of the Anuradhapura Kingdom in 993, Polonnaruwa Kingdom or the Ancient City of Polonnaruwa served as the second capital of Sri Lanka for three centuries, from the 11th to the 13th centuries. It is found in Sri Lanka's north central province. UNESCO designated Polonnaruwa as a World Heritage Site in 1982 under the name Historic City of Polonnaruwa due to its archeological importance and ancient technical supremacy. King Vijayabahu established Polonnaruwa as the first capital city after defeating Chola invaders in 1070 and reuniting the country under a native ruler. During the reign of the great King Parakramabahu, who reigned from 1153 to 1186, the nation achieved such heroic heights in rice production by building a gigantic irrigation network with reservoirs that resemble natural land seas. The remnants of the great kingdom of the Great King Parakramabahu may be found in Polonnaruwa. This kingdom's wealth and opulence are still visible. Today, the old city of Polonnaruwa is one of the country's best-planned archaeological relic sites, bearing witness to the Kingdom's early kings' discipline and magnificence. The Golden Age of Polonnaruwa was during the reign of King Parakramabahu. Under the patronage of the monarch, trade and agriculture prospered, as he was insistent that no drop of water coming from the skies be wasted, but rather utilised for the growth of the country. As a result, irrigation systems substantially better to those of the Anuradhapura period were built during Parakramabahu's reign, systems that still supply the water required for paddy farming in the country's east throughout the hot dry season. The Parakrama Samudra, or Sea of Parakrama, is the most powerful of these systems.",
          7.947684305435643,
          81.0013397671917),
      Travel(
          'Yala National Park',
          'Yala',
          'assets/images/yaka.jpg',
          "Yala National Park (also known as Ruhuna National Park) is located in Sri Lanka's south-east area and spans two provinces: southern province's Hambantota district and Uva province's Monaragala district. Palatupana, 12 kilometers from Kirinda, is the park's entrance. The distance between Colombo and the Palatupana entrance point is 305 kilometers. Tissamaharama is the entrance to Yala National Park. The Palatupana is reached after a 20-kilometer trip via Kirinda. The well-designed visitor center in Palatupana supplies travelers with information and assigns a tracker to all approaching cars. The park provides jeeps with soft tops, allowing visitors to see wildlife. The finest times for Yala Safari trips in the Yala National Park are at dawn and night. Ruhuna National Park has a hot and dry climate due to its location in one of Sri Lanka's desert areas. The average yearly temperature is 27 degrees Celsius, with temperatures reaching 37 degrees Celsius during the dry season.",
          6.368621726045042,
          81.51666410387388),
      Travel(
          'Temple of Tooth Relic',
          'Kandy',
          'assets/images/Temple_of_tooth_relic.jpg',
          "When visiting Kandy, you must pay a visit to the Temple of the Sacred Tooth Relic. It is commonly known as the Sri Dalada Maligawa and was founded in the 16th century AD. It is Sri Lanka's most venerated landmark. The temple, which is next to the old Kingdom of Kandy's royal palace complex, overlooks the enormous expanse of Kandy Lake. It was decreed that whomever shelters and guards the Buddha Relic in this sanctuary of refuge is immediately given the right to control the land. The object is a powerful emblem of Sinhalese pride and identity. Thousands of white-clad pilgrims visit this sacred site every day, bringing lotus blooms and frangipani as offerings and prayers known as pujas. Visitors and devotees come to the Temple during puja merely to look at the well-protected inner shrine where the tooth is kept, despite the fact that it is hidden behind a gold coffin. The Relic coffin is paraded through the streets on a male elephant every year during the Esala Perahera procession. The 10-day celebration is one of the world's largest Buddhist festivals, as well as Sri Lanka's most important. It is ideal to visit the Temple early in the morning or late in the evening, when the ritual offerings and prayers are made. It is critical that you are dressed adequately; your garments must cover your legs and shoulders, and your shoes must be removed before entering the sacred Temple.",
          7.293685383403623,
          80.64132050800944),
      Travel(
          'Port City',
          'Colombo',
          'assets/images/port_city.jpg',
          "Former President Mahinda Rajapaksa is said to have come up with the idea for the Port City while observing a landfill being built for the Colombo South port. China Harbour Engineering Company made a fully requested proposal based on prior ideas for the contemporary Port City. For a variety of reasons, the port city has been chastised. Many environmentalists believe that the port city is riddled with environmental risks, and that the project's negative environmental effect would outweigh any potential economic gains. Veterans of the maritime sector have warned of the hazards that handing China sole control of land, particularly in a high-security zone, may pose to Sri Lanka, as well as concerns about the impact on the country's sovereignty. The project was also chastised for its lack of openness and anomalies, such as SLPA's involvement in the reclamation project despite the fact that it had no authority to do so because its purpose is to deal with ports and shipping.",
          6.930472654831806,
          79.82910080029242),
      Travel(
          'Ruwanweli Maha Seya',
          'Anuradhapura',
          'assets/images/ruwanwelimahaseya.jpg',
          "The Ruwanweliseya is located in Anuradhapura, the ancient Sinhala capital of Sri Lanka, in the North Central Province. It was begun by King Dutugamunu (137 BC TO 119 BC) and finished after his death by his younger brother, King Saddhatissa. The Ruwanweliseya is one of the world's highest ancient structures. According to legend, King Dutugamunu constructed the Stupa on the site of a rock inscription by Arahath Mahinda. 'A great king would erect a large stupa where the stone is established,' the inscription states. In the Mahamevuna Uyana, the Ruwanweliseya is next to the Jaya Sri Maha Bodhiya. Soon after the fight with King Elara, King Dutugamunu began construction on the Great Stupa. The conflict had cost a lot of money, and times were tough, but the Mahavamsa claims that the materials required to create the Stupa mysteriously appeared from all across the island. 'To the westward of the city, at a distance of five yojanas, at the Uruvelpattana, pearls the size of 'nelli' fruit, combined with coral beads, rose to the coasts from the ocean,' according to the Mahavamsa. Part fisherman saw them and gathered them into a heap, putting (some of) the pearls and coral in a dish, and reporting the occurrence to the monarch.",
          8.350273441265093,
          80.39643307031413),
      Travel(
          'Galle Fort',
          'Galle',
          'assets/images/galle_fort.jpg',
          "Every traveller's images and words tell the tale of the Galle Dutch Fort, a UNESCO World Heritage Site. Built by the Portuguese during their conquests in the 16th century, the fort was later strengthened and seized by the Dutch in the 17th century, before falling to the British. For nearly 200 years, the old town of Galle served as a trade harbor for spices and other items. Today, however, the fort has been turned into a haven of history, romance, and beauty, where visitors are cordially invited to immerse themselves in the fascinating stories and become a part of this heritage monument. Fifty Lighthouse Street is located within the fort and provides an excellent location for exploring Galle's attractions. Stroll around the ramparts and see the majestic landmarks like as the Galle Lighthouse, Galle Clocktower, and Groote Kerk, which have been preserved in their former splendour. Only a resident from within the fort would know the secrets revealed on a Galle Fort Walking Tour with us. Our walking tour takes you through the backstreets of this historic fort, stopping at lovely structures, museums, old buildings, and more while listening to infinite stories, mysteries, and secrets of the Galle Dutch Fort.",
          6.030334441263418,
          80.21604445949421),
      Travel(
          'Hikkaduwa Coral Reef',
          'Hikkaduwa',
          'assets/images/hikkaduwa_coral_reef.jpg',
          "Hikkaduwa Coral Garden is located 98 kilometers south of Colombo and is easily accessible by road and train. The Hikkaduwa Coral Sanctuary is located a few hundred meters off the coast of Hikkaduwa. The Coral Sanctuary is one of the country's most popular and well-known coral reef locations, drawing visitors from all over the world for a variety of reasons. Hikkaduwa is a typical shallow fringing reef, with an average depth of roughly 5 meters (16 ft). The coral reef acts as a natural breakwater and decreases coastal erosion. The national park's seashore stretches about four kilometers. The coast is generally narrow, with widths varying from 5 to 50 meters depending on the season. Scuba diving is a common pastime in this area. Hikkaduwa National Park is one of Sri Lanka's two maritime national parks. A bordering coral reef with a high degree of biodiversity may be found in the national park. On May 18, 1979, the region was designated as a wildlife sanctuary, and on August 14, 1988, it was upgraded to a nature reserve with expanded land area. In the next 25 years, the number of visitors will increase, causing the coral reef to deteriorate. On September 19, 2002, the reef was designated as a national park in order to mitigate the effects on the ecology.",
          6.135314843335544,
          80.09946445440035),
      Travel(
          'Thalpe Beach',
          'Galle',
          'assets/images/thalpe.jpg',
          "Thalpe Beach is a beach in Sri Lanka's southern province of Galle, adjacent to the city. It's a popular tourist spot for both residents and visitors. Thalpe's surroundings have colorful shops, restaurants, and a variety of water sports-related activities. Thalpe is a tranquil village tucked away from the rush and bustle of the southern coastal belt's big cities. Thalpe village has a lot of history, adventure, culture, and food to offer, as well as Thalpe Beach, which is generally clean and tranquil. Stilt fishermen are widespread in this coastal village, and they are a terrific way to discover more about the way of life in this lovely town. The rock ponds were carved out of the corals some 50 years ago, according to the islanders, and were used to soak coconut husks in order to extract the coconut coir. From March to April, the ideal time to explore Rock Pool Beach is early in the morning. At other times, the pools are sand-filled.",
          5.995289358929279,
          80.28789252198033),
      Travel(
          'Unawatuna Beach',
          'Galle',
          'assets/images/unawatuna_beach.jpg',
          "Unawatuna is one of Sri Lanka's most popular tourist sites and the country's most 'renowned' beach. It's a beautiful banana-shaped beach with golden sand and blue sea, all encircled by lush green palm trees! It was our first stop on the island of Sri Lanka. We opted for a guesthouse a few kilometers away from the beach of Unawatuna, rather than one of the posh and pricey hotels near the beach. On two different day outings, we walked to Unawatuna Beach.",
          6.009851276890086,
          80.24837310439976),
    ];
  }

  static List<Travel> generateMostPopular() {
    return [
      Travel(
          'Pahan Thudawa',
          'Belihuloya',
          'assets/images/pahan thudawa.jpg',
          "Pahanthudawa is another one-of-a-kind and spectacular waterfall in Sri Lanka. The rationale for its position and nature, as well as the name of this waterfall, comes from its natural setting. Pahanthudawa Falls gets its name from this. The Pahanthudawa waterfall is located in Belihuloya, in the Samanalawewa Tourist Zone of the Sabaragamuwa Province's Ratnapura District. The distance between Colombo to Belihuloya is 144.5 kilometers. Take the Colombo – Batticaloa Highway from Colombo to Belihuloya to reach the Pahanthuda Waterfall. Pahanthudawa Falls is 1.5 kilometers from Belihuloya and takes around 10 minutes to get to. Any day except rainy days is the finest time to see Pahanthudawa Waterfall.",
          6.725984215087579,
          80.75890215496291),
      Travel(
          "Baker's Bend",
          'Nonperial',
          'assets/images/Bakers bend.jpg',
          "Bakers Bends is a gorgeous tourist attraction in the lovely Belihuloya Nanperial Estate in the Baragamuwa Province's Ratnapura District. It is situated in the Horton Plains' foothills. It sits at a height of around 5,000 feet above sea level. We can reach the entrance of this Nanperiyak estate after traveling through Belihuloya on the Colombo-Badulla route for a few kilometers. At the Nanperial curve, the Nanperial path begins. Bakers Bend is located at the head of this road. Because the Bakers Bend is on the Nanperial Estate, you'll need to obtain permission from the estate office and then go up. Bakers Bend is roughly a two-hour drive from the parking lot.",
          6.761107442298328,
          80.78363111263388),
      Travel(
          'Surathali ella',
          'Kalupahana',
          'assets/images/surathali ella.jpg',
          "Surathali Ella is a stunning waterfall in Ratnapura District, located across the A4 road passing through Belihuloya (7.5km from the Pambahinna junction and 13.5km from the Beragala junction), with a height of 60 meters, a width of 2 meters, and three distinct parts. The waterfall was given the name 'Surathali Ella' after a movie that was filmed in the vicinity.",
          6.746084377282115,
          80.82885685496302),
      Travel(
          'Bakers Falls',
          'Hortain Plain',
          'assets/images/bakers_fall.webp',
          "Gonagala Falls is the original name of this lovely waterfall. There are two drops in this cascading waterfall. Sir Samuel Baker, a British native who found it in 1845, gave it its current name. In the park, he was also known for murdering 50 elephants. Belihul Oya makes this pretty loud waterfall by smashing the water into a big rock structure at the bottom. Despite how lovely Baker's Falls is, the plunge pool around it is reputed to be a 12m deep death trap where many people have perished in the past. Baker's Falls is 3.3 kilometers from the trailhead on the Horton Plains National Park's famed walk to witness the Great World's End Drop. The average temperature in the park is approximately 16°C, and rain is forecast for the majority of the year. The final section of the trail leading to the fall is a root-strewn one with a downhill descent, which may be quite difficult in wet weather.",
          6.793000940166343,
          80.78955185681102),
      Travel(
          '18 Bend',
          'Mahiyanganaya',
          'assets/images/18 bend.jpg',
          "Daha ata wanguwa (18 Bend Route) is a well-known asphalted road that connects Kandy with Mahiyanganaya in Sri Lanka's Central Province, a central hilly environment. The route is 41 kilometers long and features 17 hairpin turns. The portion of the A26 road, which connects Kandy with Mahiyanganaya, has been upgraded (reasphalted and enlarged) in recent years. It's also known as the 18 hairpin curve road, and it's considered one of the most challenging routes in the country by many drivers. The legendary 18 hairpin curves made it a tough route for even experienced drivers, and it became one of the places where they could put their driving talents to the test. However, for more than a century and a half, this was the sole route that connected these major cities. Though it is known as the 18 bend road, there are only 17 curves in actuality since one bend was eliminated long ago after the route was widened.",
          7.353741720398267,
          80.91797492426454),
      Travel(
          'Adhisham Bunglow',
          'Haputale',
          'assets/images/adhisham.jpg',
          "The Adisham Bungalow was previously Sir Thomas Lester Villiers' country residence, but now it houses the St. Benedict's Adisham Monastery. The Adisham Bungalow, located barely 3 kilometers from Haputale town, is one of the region's most scenic spots. The home, built in 1931, was planned in the Tudor style and modeled after Leeds Castle in Kent; Sir Thomas Villiers even called it after the hamlet where he was born, and it has all the trappings of an English manor. The Bungalow has a large library that is stocked to the brim with old dusty books that the planter treasured. Tourists are only permitted to see the library and living room of the home, but there is an attached guest house where visitors are more than welcome to stay.",
          6.772678682444292,
          80.93093359729234),
      Travel(
          'Bahirawakanda Temple',
          'Kandy',
          'assets/images/bahirawakanda.jpg',
          "The Sri Maha Bodhi Viharaya, located on the hill of Bahirawakanda, is well known to tourists for its massive Buddha statue, which can be viewed from practically anywhere in Kandy. The statue, which was completed in 1972, depicts Lord Buddha in the Nirvana attitude, which is the position connected with his first Enlightenment. It is one of the tallest Buddha sculptures in Sri Lanka, standing at more than 25 meters. The name Bahirawakanda means 'Gnome Mountain', and it refers to the stories that surround the temple's hill. Villagers in the surrounding villages used to think that the hill was home to an evil gnome that preyed on unwary victims. The people would sacrifice a virgin girl (or multiple virgins, depending on the version of the story) to the hill in order to satisfy it. The locals' superstition and dread of the hill lessened with time.",
          7.295785717004137,
          80.63101367400313),
      Travel(
          "Elle Wala Waterfall",
          'Ella',
          'assets/images/ella wala.jpg',
          "Ellewala Ella is a tiny yet lovely waterfall in the Monaragala District that may be reached through the Ella – Wellawaya Road. About 5 kilometers from Wellawaya Town, this waterfall is concealed among the woods. The Ellewala Falls in Ratnapura District are included on the LCWF. This might be a typo or a separate but undiscovered Elle Wala Waterfall. The Monaragala District is home to the Ellewala Ella mentioned here. To go to the Rathmal Vehera Ancient Temple from Wellawaya, use the Ella Road for 3 kilometers. Take the road that runs next to the temple and leads to the waterfall. The last few kilometers are supposed to be rocky and unsuitable for low-ground-clearance vehicles. You may need a 4×4 will need to travel by a 3 wheeler. To reach the fall, you will need to walk few hundred meters in to the jungle.",
          6.781637924306894,
          81.08580369729242),
      Travel(
          'Idalgashinna Railway Station',
          'Idalgashinna',
          'assets/images/idalgashinna.jpg',
          "Idalgashinna Railway Station, located between Haputale and Ohiya railway stations, is generally referred to as Sri Lanka's most attractive railway station. The station dates from the colonial era and was built in 1893 when the railway route from Nanu Oya to Haputale was expanded. Between Ohiya and Idalgashinna, the station is known for having 14 tunnels, which makes it the station with the most tunnels between two railway stations in Sri Lanka. Idalgashinna Station is a modest station that is dwarfed by the pine-forested hill that towers behind it. The entire station has only one platform, and as soon as you exit the train, all you see are vast green hills with a few scattered houses peeking through the foliage. Because the station is engulfed in a dense cloud of mist in the late afternoons and nights, the ideal time to come is in the morning, especially during dawn. Despite the limited vision, seeing the mist sweep in and cover everything in a veil of white is amazing.",
          6.779597171435391,
          80.8970761703048),
      Travel(
          "Narangala Mountain",
          'Badulla',
          'assets/images/narangala.JPG',
          "In the Thangamalai Estate area, the trekking track begins. The name is derived from the golden grasses that clothe the slopes of Narangala and means 'Golden Mountain' in Tamil. Narangala's sharply rectangular summit is one of its most distinguishing features, making it a pleasing appearance even from afar. Hikers should park their cars at the estate's Hindu Temple. If you don't have a guide, several locals may gladly point you in the right direction. You'll have to ascend through the tea plantation on little foot pathways until you come across a massive pipe line that provides the estate with water. The pipe will then be followed until it reaches a road that passes through the estate. There will be several picturesque vistas of hills covered in the vivid green of tea plants that you may shoot. After a short distance on the estate road, you will arrive at the place where you will begin the ascent up the mountain.",
          7.038938947120858,
          81.01316938669736),
      Travel(
          'Nelligala Temple',
          'Kandy',
          'assets/images/nelligala.JPG',
          "Nelligala Temple is located 700 meters above sea level in the hamlet of Murutalawa, 11 kilometers from Kandy and 7 kilometers from Peradeniya. The Nelligala temple, which was built in 2015, is located on the summit of the Nelligala rock, which is surrounded by the mountain ranges of Alagalla, Hanthana, Hunnasgiriya, Batalegala, and Atipala. In the fullest meaning of the term, the Nelligala International Buddhist Center is a hallowed location. The Nelligala Sacred Area was established in 2014 after a scrub woodland was preserved. It is worth mentioning that the forest has been preserved here. The construction of this hallowed site in the center of the blue mountain range required six years of effort. The sculptures and patterns here are golden, and the bodhi tree in a big gold basin is particularly noteworthy. Among the other gold-on-blue sculptures, the seventy-foot-high bubble-shaped pagoda sticks out. The stupa was also built in three months, which was a pleasant surprise.",
          7.302278650828588,
          80.5601648933467),
      Travel(
          'Nil Diya Pokuna',
          'Ella',
          'assets/images/nil diya pokuna.jpg',
          "Nildiya Pokuna, which is 13.3 kilometers from Ella, is an excellent site to enjoy an adventure experience. According to legend, King Rawana took Sita from India and housed her in a luxurious and secure environment. Many people claim that the location is now a wrecked subterranean palace complex with blue water flowing through it. This is a high-risk venture that is well worth the effort. You can have this experience as soon as possible, but please do not desecrate the environment. According to legend, King Rawana took Sita from India and housed her in a luxurious and secure environment. Many people claim that the location is now a wrecked subterranean palace complex with blue water flowing through it. According to legend, King Rawana kidnapped Goddess Sita and hid her in this cave. According to legend, there were multiple tunnels beneath this rock that went for kilometers. The Ravana Ella cave's tunnels to Nuwara Eliya's chilly light near the Bogoda Rajamaha Viharaya and the Dowa Rajamaha Viharaya may still be seen today. It's also a memory that bears testimony to what happened. In addition, the tunnel is thought to have been built to reach numerous more sites hundreds of feet beneath the surface. According to legend, it contains a throne and a crown. The tunnels were blocked under the cover of the Police Special Task Force, thus no further action was taken.",
          6.83559440942759,
          81.0638659126343),
      Travel(
          "Sorabora Wewa",
          'Mahiyanganaya',
          'assets/images/sorabora wewa.jpg',
          "The famed Sorabora Wewa, a historic Bintanne irrigation reservoir, is located approximately 1 km from Mahiyangana town and is a must-see for tourists visiting Mahiyangana Rajmaha Viharaya. Sorabora Wewa, also known as the Sea of Binthanne in ancient times, is unique among ancient reservoirs in that it is the only one that does not employ a Bisokotuwa, which is the heart of all other significant reservoirs in the country. Since the 4th century BC, this ground-breaking technology has been the sole factor that has allowed the ancients to construct huge reservoirs. The sluice gates for the Sorabora Wewa were not placed on the embankment; instead, they were carved into a strategically situated natural rock away from the embankment and utilized as the sluice for the tank. The ancient builders opted to forego the tried and true Bisokotuwa for this construction since the rock was not vulnerable to erosion by water pressure. The Sorabora Tank is a 1590-foot (485-meter) embankment that dams the Diyawant to Oya. At maximum capacity, the tank covers 1100 acres (4.5 square kilometers) and stores 11800 acre feet (14.6 million square meters) of water. The slicing gates are around 5 feet wide and neatly carved into the natural granite.",
          7.3674423521232795,
          81.01738476393591),
      Travel(
          'Victoria Dam',
          'Theldeniya',
          'assets/images/victoria dam.jpg',
          "Victoria Dam is a 10-mile-long arch dam in Kandy. It's 130 miles (209 kilometers) upstream from the mouth of the Mahaweli River and 4 miles (6 kilometers) from Teldeniya. Irrigation and hydroelectric power generation are two of its primary functions. It is Sri Lanka's tallest dam, and it houses the country's largest hydroelectric power facility, with a capacity of 210 megawatts. The dam's construction began in 1978 and was finished in April 1985. The river's catchment area above the dam site is 730 square miles. The Polgolla dam, which can divert a maximum flow of 2,000 cusecs, has been built and is operational upstream of this location. Comprehensive research and feasibility studies for the construction of a dam over the Kotmale Oya. The preparations for a significant upper right bank tributary of the Mahaweli Ganga are nearing completion. The reservoir's drainage region is located in the central hills, with elevations of up to 8,000 feet. The long-term mean annual flow at the dam site is 2,430 thousand acre feet, with 1.100 thousand acre feet diverted at Polgolla at the moment.",
          7.241460846526643,
          80.78514045496571),
      Travel(
          'Rawana Cave',
          'Ella',
          'assets/images/ravana cave.jpg',
          "Ravana Cave is a significant sight in Ella, and is linked to King Ravana of the classic Indian epic Ramayana. The Demon King is claimed to have kidnapped the Indian Princess Sita and hidden her in the cave, according to tradition. According to legend, this was done as a form of vengeance against Rama, Princess Sita's consort, for chopping off his King Ravana's sister's nose. Human settlement dates back to 20,000 BC, according to excavations in this ancient cave. The cave is 50 feet wide, 150 feet long, and 60 feet high, and is 1, 370 meters (4, 490 feet) above sea level. The cave is also said to be linked to the Dowa Rock Temple cave near Badulla. Ravana Falls, a 25-meter waterfall, is located behind the cave (Ravana Ella). The magnificent waterfall is one of Sri Lanka's largest, especially during the rainy season. Princess Sita is supposed to have taken a bath in a pool of water created by the waterfall.",
          6.8647342412089,
          81.04869534146985),
      Travel(
          "Sera Ella",
          'Matale',
          'assets/images/sera ella.jpg',
          "The Sera Ella Falls are located in the middle of Matale District, close to the town of Laggala. With a quiet clamor, the waterfalls tumble down a large rocky cliff and delicately land on a pool of water. The Puwakpitiya River is formed by the confluence of two rivers, which result in the Puwakpitiya Falls. With its flawless presence and pure beauty, it dwarfs many higher waterfalls while being barely 10 meters tall. The falls have become a prominent tourist attraction as a result of its unusual characteristics. It is also well-known for the hiking options it provides.",
          7.588501931537712,
          80.75497812613236),
      Travel(
          'Surathali ella',
          'Kalupahana',
          'assets/images/surathali ella.jpg',
          "This waterfall is closer to the major road (A4) between Colombo and Badulla, and the top section of it may be viewed from the road. After passing through the famed Belihuloya rest house on the A 4 route towards Badulla, there are a few kilometers to drive. The waterfall is marked with a name board on the left side of the road. To get there, you'll have to go roughly 50 meters. It is also feasible to reach the peak by walking through the jungle on a foot trail. The curve of this waterfall is not entirely vertical. It flows over a rock with an angled form. Because the water stream comes from the natural forests of Horton Pains, this 50 m tall marvel contains clean cold water. This is one of the few waterfalls that is easily accessible from the road.",
          6.74610568639088,
          80.82883539729224),
      Travel(
          'Dondra Head Lighthouse',
          'Matara',
          'assets/images/dondra_head_lighthouse.jpg',
          "The Dondra Head Lighthouse is the island's highest lighthouse, reaching at 160 feet. It is considered one of the most iconic lighthouses on the entire island. It also serves as one of the most significant lighthouses still in service, due to its location on Sri Lanka's southernmost tip. The lighthouse has seven storeys, which are accessible through a 196-step stairwell that may be rather taxing on the legs if climbed all the way to the top. The view from the summit is just beautiful, and if you look north, you can even see the Bulutota Mountain Range. Keep in mind, however, that entry to the summit is only possible with specific clearance.",
          5.91898997325487,
          80.59124107030038),
      Travel(
          'Hummanaya',
          'Matara',
          'assets/images/hummanaya.jpg',
          "Discover the Hummanaya Blow Hole, the world's second biggest and the largest in Sri Lanka alone, while exploring the southern coast! The Hummanaya Blow Hole is located in Kudawella, a tiny village just outside of Matara, and can be reached by taking a short 5-10 minute stroll through a small, calm village populated with local sellers offering handicrafts, street food, and cool beverages. As you walk down the trail leading to the attraction, take in the breathtaking views of the azure shoreline. Before reaching this natural site, hike across tough terrain after passing through the main gate and ticket office. Tourists come from all over the world to see the blow hole and marvel at its beauty. The Hummanaya Blow Hole is a natural marvel that shoots a jet of sea water into the air between two massive boulders, reaching heights of over 80 - 100 feet at times. It should be on your list of things to see while staying with us in Mirissa. During high tide, you can feel the salty spray on your skin as seawater soars towards the sky and crashes back on its wide-eyed audience.",
          5.978721524770789,
          80.73749505654507),
      Travel(
          "Mirissa Whale Watching",
          'Mirissa',
          'assets/images/mirissa whale watching.jpg',
          "Set out on a calm trip to the depths of the Indian Ocean in quest of the fascinating species that live beneath the turquoise waters' surface. Between November and April, Mirissa is the best area to go whale and dolphin watching, as the seas become a playground for a variety of whale and dolphin species. Sperm whales, killer whales, Bryde whales, and short-finned whales are among of the most regularly seen whales, while schools of bottlenose dolphins and striped dolphins will joyously cavort about your boat! The blue whale, the world's biggest species, is the major whale to keep an eye out for. As they set out into the ocean, nature enthusiasts may enjoy whale and dolphin watching in Mirissa. The optimum time to start your experience is first thing in the morning, and because most boats leave the port by at least 6 a.m., you'll need to get up early. Make a reservation at one of our Mirissa boutique hotels to save the extra travel time and get a few more zzz's before your day at the beach!",
          5.9482409366437095,
          80.45025224345035),
      Travel(
          'Samanala Wewa Dam',
          'Belihuloya',
          'assets/images/Samanalawewa dam.jpg',
          "The Udawalawa basin has the Samanala dam. It was constructed near the junction of the Walawe and Belihuloya rivers, 400 meters above sea level. It is also close to the town of Balangoda. In Sri Lanka, the Samanala dam is primarily utilized for hydroelectric power generation. The Samanalawewa project, which produces 405GWh of electricity annually, is the country's third-largest hydroelectric scheme. A big leak caused a landslide on the right bank, around 300 meters downstream from the dam. The 2100 litres per second leak persists, although it has had no effect on electricity output at the facility, which has been operational since its commissioning in 1992.",
          6.679135239694101,
          80.79935386845645),
      Travel(
          'Weherahena Temple',
          'Matara',
          'assets/images/ravana cave.jpg',
          "Weherahena (Veherahena) is a prominent Buddhist pilgrimage site. The temple's tale is fascinating, despite the fact that it has little historical relevance. Furthermore, the temple is considered to be the world's largest and first tunnel temple. Despite the fact that it is stated that this temple was built out of adobe to arhath bikkus in ancient Sri Lanka, the temple's tale begins in the early twentieth century. In the early part of the century, his master dispatched the Most Rev. Parawahera Rewatha Thero to the Weherahena region as a punishment. Weherahena was nothing more than a half-acre of dense jungle with a single Bodhi Tree. According to legend, Ven. He managed to organize the people and construct a little clay home for himself, but he soon had the magnificent idea of erecting the world's largest Buddha statue. He also desired to construct a tunnel temple, as shown in the Ummaga Jathaka myth.",
          5.953251415180858,
          80.57526453961742),
      Travel(
          "Devil’s Staircase",
          'Kalupahana',
          'assets/images/devils stair case.jpg',
          "Several natural and man-made structures across the world have been dubbed 'the Devil's Staircase.' Sri Lanka has one of the most deadly among them. This well-known track is a 14-kilometer long series of abrupt zig-zag curves that are exceedingly steep and difficult to navigate, but extremely exhilarating. The route starts on the Horton Plains road in Ohiya and travels through tea farms to the Kalupahana district on the A4 Main Road; or vice versa. You can alternatively conclude the route around Bambarakanda Falls, which is about a kilometer before Kalupahana. The Devil's Staircase can be climbed or navigated by a 4WD vehicle since, despite its acceptable width, it is rather uneven in certain parts. Along the way, there are some stunning views and other intriguing sights to visit.",
          6.806873884894431,
          80.84168651963648),
      Travel(
          'Browns Beach',
          'Negombo',
          'assets/images/negembo-beach.jpg',
          "Negombo, six kilometers from Sri Lanka's international airport, is a typical mostly Christian fishing town with tiny alleys and modest stores, as well as several ancient churches to visit and view, with paths dating back to the advent of the Portuguese. Negombo is a great spot to experience Sri Lanka's traditional fishing methods, such as outrigger canoes, swifter catamarans, and the lagoon, which is known for its promfret, lagoon crab, and lobster throughout the season. A tourist town with several hotels and restaurants, as well as the famous lagoon, where visitors may take a trip in an outrigger sailing canoe and experience the true life of a fisherman.",
          7.23905648457663,
          79.8402454549134),
      Travel(
          'Lipton Seat',
          'Haputale',
          'assets/images/lipton seat.webp',
          "The most popular attraction in Haputale is Lipton's Seat. Lipton's Seat is a viewpoint named after the famous Thomas Lipton and is about an hour from Haputale town. He was a Scottish trader who traveled to British Ceylon in 1890 and met James Taylor, with whom he collaborated to establish tea gardens to the nation. Taylor had attempted to cultivate coffee on the island before to Lipton's arrival, but the crops were destroyed by a leaf-blight. The two men began on a commercial enterprise that would outlast their lives with Lipton's assistance. Thomas Lipton would sit with a cup of tea in hand and proudly look over his land from Lipton's Seat, a popular vantage point. The overlook still offers one of the greatest views, and there's even a life-sized statue of Lipton on a seat where you can snap photos! It is best to visit early in the morning to escape the crowds and late-morning fog.",
          7.23905648457663,
          79.8402454549134),
    ];
  }
}
